### ISSUE TITLE
ViewBinding代理转换异常

### ISSUE THREAD

**Issue by Reginer** [pengxurui/pengxurui#1]
在BaseActivity中使用LayoutInflater.from的形式，如果activity的外层布局和base_layout的布局不是同一类型，会出现布局转换异常

**Comment by pengxurui** [comment]
你的问题似乎可以用另一个 API 解决：

[ViewBindingProperty](https://github.com/pengxurui/DemoHall/blob/main/KotlinDelegate/ktx/src/main/java/com/xurui/ktx/property/ViewBindingProperty.kt)

```
@JvmName("viewBindingActivity")
inline fun <A : ComponentActivity, V : ViewBinding> viewBinding(
    crossinline viewBinder: (View) -> V,
    @IdRes viewBindingRootId: Int
): ViewBindingProperty<A, V> = ActivityViewBindingProperty { activity: A ->
    viewBinder(activity.requireViewByIdCompat(viewBindingRootId))
}

```
你可以指定需要绑定的视图的 id，而不用局限于 ContentView，试试看吧！

**Comment by Reginer** [comment]
先说一个前提，BaseLayout是一个库里的，类似所有封装getLayoutId一样的写法，所以设置setContentView这一步其实不是我显式设置的。

另外已经传了layoutId了，同时也给定 ViewBinding了，还要再传个 viewBindingRootId 这恐怕不是个可取的方案。

和base_layout同样的布局可以使用，不传viewBindingRootId理论上也是可以实现的。

之后我再看看，改好了给你提pr。
